### ISSUE TITLE
Use a different logo for the vscode plugin

### ISSUE THREAD

**Issue by ryyppy** [anthonypenna/rescript-light-theme#1]
Hi Anthony,

I just saw on the VSCode store that your plugin is using the official ReScript logo as an icon, so I wanted to reach out and ask if you could publish a version that uses a clearly modified version of the logo, so it doesn't look like an official tool? 

Right now this is what the store shows:
![image](https://user-images.githubusercontent.com/1121889/120965359-16054300-c765-11eb-896c-b77aeec7fe01.png)

Which might be misleading, since we don't curate any themes.

Sorry to bother you with this; we didn't have time yet to define our usage guidelines for the logo, so we are reaching out on an individual basis if we see some issues.

Cheers

**Comment by anthonypenna** [comment]
Cheers mate, will do asap!

**Comment by anthonypenna** [comment]
@ryyppy Updated the logo, let me know if there are any issues with it!
![Schermata 2021-06-07 alle 11 15 40](https://user-images.githubusercontent.com/31355705/120991245-bd906e80-c781-11eb-9c33-472132bee1ef.png)

**Comment by ryyppy** [comment]
perfect! looks gorgeous!
