### ISSUE TITLE
how to customize some colors

### ISSUE THREAD

**Issue by vasco3** [anthonypenna/rescript-light-theme#2]
Can you give me guidance on which attributes I can change to customize some colors on the rescript code?

I would like to give more contrast to the main font color using settings.json at user level, but I'm having trouble finding which attribute will override the rescript-light-theme

**Comment by anthonypenna** [comment]
Hi @vasco3, you can easily customize the theme by heading to [this online vscode theme editor](https://themes.vscode.one/theme/anthonypenna/RegjOQTI).

At the top you should see a red button that says `Fork`, which will automatically copy the theme to your account and from there you can make all the changes you want.
